name: depiproject
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adhan: ^2.0.0+1
  adhan_dart: ^1.1.2
  audio_session: ^0.1.16
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  device_preview: ^1.2.0
  dio: ^5.9.0
  easy_date_timeline: ^2.0.9
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_qiblah: ^3.1.0+1
  flutter_slider_drawer: ^3.0.2
  font_awesome_flutter: ^10.9.0
  geocode: ^1.0.3
  geocoding: ^4.0.0
  geolocator: 13.0.4
  get: ^4.7.2
  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.0
  islamic_hijri_calendar: ^0.0.4
  just_audio: ^0.9.36
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  pull_to_refresh: ^2.0.0
  share_plus: ^12.0.1
  sleek_circular_slider: ^2.0.1
  swipe_refresh: ^1.1.2
  table_calendar: ^3.2.0
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/doaa.json
  fonts:
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
